spring:
  profiles: default
  application:
    name: TimeRecording Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/worklog
    username: worklog
    password: worklog
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 2324